# Generated by Django 3.1.5 on 2021-02-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='Stu',
        ),
    ]
